## Base16 Modus Operandi (Deuteranopia)
# Author: emacs people
[general]
background = "#ffffff"
border = "#ffffff"
horizontal_rule = "#d6d6d6"
unread_indicator = "#87af00"

[text]
primary = "#000000"
secondary = "#ffffff"
tertiary = "#87af00"
success = "#5f875f"
error = "#d70000"

[buffer]
action = "#5f875f"
background = "#ffffff"
background_text_input = "#eaeaea"
background_title_bar = "#eaeaea"
border = "#bfbfbf"
border_selected = "#ffffff"
code = "#af5fff"
highlight = "#d70000"
nickname = "#5fafff"
selection = "#bfbfbf"
timestamp = "#000000"
topic = "#808080"
url = "#005faf"

[buffer.server_messages]
join = "#5f875f"
part = "#d70000"
quit = "#d70000"
default = "#5fafff"

[buttons.primary]
background = "#ffffff"
background_hover = "#bfbfbf"
background_selected = "#d6d6d6"
background_selected_hover = "#808080"

[buttons.secondary]
background = "#eaeaea"
background_hover = "#ffffff"
background_selected = "#d6d6d6"
background_selected_hover = "#808080"
