# Base16 Modus Vivendi (Deuteranopia) - alacritty color config
# emacs people

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x000000'
foreground = '0xffffff'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x000000'
cursor = '0xffffff'

# Normal colors
[colors.normal]
black = '0x000000'
red = '0xff5f59'
green = '0x44bc44'
yellow = '0xcabf00'
blue = '0x2fafff'
magenta = '0xfeacd0'
cyan = '0x00d3d0'
white = '0xffffff'

# Bright colors
[colors.bright]
black = '0x1e1e1e'
red = '0xff5f5f'
green = '0x44df44'
yellow = '0xefef00'
blue = '0x338fff'
magenta = '0xff66ff'
cyan = '0x00eff0'
white = '0x989898'
