# Base16 Modus Operandi (Deuteranopia) 256 - alacritty color config
# emacs people

# Default colors
[colors.primary]
background = '0xffffff'
foreground = '0x721045'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xffffff'
cursor = '0x721045'

# Normal colors
[colors.normal]
black = '0xffffff'
red = '0xf2f2f2'
green = '0x808000'
yellow = '0x008900'
blue = '0xdd22dd'
magenta = '0x008899'
cyan = '0x0000ff'
white = '0x721045'

# Bright colors
[colors.bright]
black = '0x695500'
red = '0xf2f2f2'
green = '0x808000'
yellow = '0x008900'
blue = '0xdd22dd'
magenta = '0x008899'
cyan = '0x0000ff'
white = '0x000000'

[[colors.indexed_colors]]
index = 16
color = "0xd00000"

[[colors.indexed_colors]]
index = 17
color = "0x595959"

[[colors.indexed_colors]]
index = 18
color = "0xa60000"

[[colors.indexed_colors]]
index = 19
color = "0x006800"

[[colors.indexed_colors]]
index = 20
color = "0x0031a9"

[[colors.indexed_colors]]
index = 21
color = "0x005e8b"
