# Base16 Harmonic Light - alacritty color config
# Jannik Siebert

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xF7F9FB'
foreground = '0x405c79'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xF7F9FB'
cursor = '0x405c79'

# Normal colors
[colors.normal]
black = '0xF7F9FB'
red = '0xbf8b56'
green = '0x56bf8b'
yellow = '0x8bbf56'
blue = '0x8b56bf'
magenta = '0xbf568b'
cyan = '0x568bbf'
white = '0x405c79'

# Bright colors
[colors.bright]
black = '0xaabcce'
red = '0xbfbf56'
green = '0xE5EBF1'
yellow = '0xcbd6e2'
blue = '0x627e99'
magenta = '0x223b54'
cyan = '0xbf5656'
white = '0x0b1c2c'
