# Base16 Modus Vivendi (Deuteranopia) - alacritty color config
# emacs people

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x000000'
foreground = '0xfeacd0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x000000'
cursor = '0xfeacd0'

# Normal colors
[colors.normal]
black = '0x000000'
red = '0xf2f2f2'
green = '0x44df44'
yellow = '0xff5f5f'
blue = '0xff66ff'
magenta = '0x00eff0'
cyan = '0xefef00'
white = '0xfeacd0'

# Bright colors
[colors.bright]
black = '0xcabf00'
red = '0x1e1e1e'
green = '0xff5f59'
yellow = '0x44bc44'
blue = '0x2fafff'
magenta = '0x00d3d0'
cyan = '0x989898'
white = '0xffffff'
