# Base16 Modus Operandi (Deuteranopia) - alacritty color config
# emacs people

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xffffff'
foreground = '0x721045'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xffffff'
cursor = '0x721045'

# Normal colors
[colors.normal]
black = '0xffffff'
red = '0xf2f2f2'
green = '0x808000'
yellow = '0x008900'
blue = '0xdd22dd'
magenta = '0x008899'
cyan = '0x0000ff'
white = '0x721045'

# Bright colors
[colors.bright]
black = '0x695500'
red = '0xd00000'
green = '0xa60000'
yellow = '0x006800'
blue = '0x0031a9'
magenta = '0x005e8b'
cyan = '0x595959'
white = '0x000000'
