# Base16 Modus Vivendi (Deuteranopia) 256 - alacritty color config
# emacs people

# Default colors
[colors.primary]
background = '0x000000'
foreground = '0xfeacd0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x000000'
cursor = '0xfeacd0'

# Normal colors
[colors.normal]
black = '0x000000'
red = '0xf2f2f2'
green = '0x44df44'
yellow = '0xff5f5f'
blue = '0xff66ff'
magenta = '0x00eff0'
cyan = '0xefef00'
white = '0xfeacd0'

# Bright colors
[colors.bright]
black = '0xcabf00'
red = '0xf2f2f2'
green = '0x44df44'
yellow = '0xff5f5f'
blue = '0xff66ff'
magenta = '0x00eff0'
cyan = '0xefef00'
white = '0xffffff'

[[colors.indexed_colors]]
index = 16
color = "0x1e1e1e"

[[colors.indexed_colors]]
index = 17
color = "0x989898"

[[colors.indexed_colors]]
index = 18
color = "0xff5f59"

[[colors.indexed_colors]]
index = 19
color = "0x44bc44"

[[colors.indexed_colors]]
index = 20
color = "0x2fafff"

[[colors.indexed_colors]]
index = 21
color = "0x00d3d0"
