# Base16 Modus Operandi (Deuteranopia) 256 - alacritty color config
# emacs people

# Default colors
[colors.primary]
background = '0xffffff'
foreground = '0x000000'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xffffff'
cursor = '0x000000'

# Normal colors
[colors.normal]
black = '0xffffff'
red = '0xd70000'
green = '0x5f875f'
yellow = '0x87af00'
blue = '0x005faf'
magenta = '0xaf5fff'
cyan = '0x5fafff'
white = '0x000000'

# Bright colors
[colors.bright]
black = '0xbfbfbf'
red = '0xd70000'
green = '0x5f875f'
yellow = '0x87af00'
blue = '0x005faf'
magenta = '0xaf5fff'
cyan = '0x5fafff'
white = '0xffffff'

[[colors.indexed_colors]]
index = 16
color = "0xd75f00"

[[colors.indexed_colors]]
index = 17
color = "0xffaf00"

[[colors.indexed_colors]]
index = 18
color = "0xeaeaea"

[[colors.indexed_colors]]
index = 19
color = "0xd6d6d6"

[[colors.indexed_colors]]
index = 20
color = "0x808080"

[[colors.indexed_colors]]
index = 21
color = "0x3c3c3c"
