# Scheme name: penumbra balanced eight light
# Scheme system: 
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

$ENV:FZF_DEFAULT_OPTS=@"
--color=bg:#FFF7ED,fg:#3E4044,hl:#8D9741
--color=bg+:#BEBEBE,fg+:#,hl+:#
--color=info:#9481CC,border:#9481CC,prompt:#47A477
--color=pointer:#5794D0,marker:#,spinner:#,header:#CA736C
"@
