# Scheme name: penumbra contrast++ eight dark
# Scheme system: 
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

$ENV:FZF_DEFAULT_OPTS=@"
--color=bg:#181B1F,fg:#F2E6D4,hl:#A9B852
--color=bg+:#636363,fg+:#,hl+:#
--color=info:#B69CF6,border:#B69CF6,prompt:#54C794
--color=pointer:#6EB2FD,marker:#,spinner:#,header:#F58C81
"@
