# -penumbra contrast+ eight light
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

export FZF_DEFAULT_OPTS=" \
 --color=bg:#FFF7ED,fg:#3E4044,hl:#9CA748\
 --color=bg+:#CECECE,fg+:#3E4044,hl+:#\
 --color=info:#,border:#61A3E6,prompt:#50B584\
 --color=pointer:#FFF7ED,marker:#,spinner:#,header:#DF7F78"
