# -penumbra contrast+ eight dark
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

export FZF_DEFAULT_OPTS=" \
 --color=bg:#24272B,fg:#F2E6D4,hl:#9CA748\
 --color=bg+:#636363,fg+:#F2E6D4,hl+:#\
 --color=info:#,border:#61A3E6,prompt:#50B584\
 --color=pointer:#24272B,marker:#,spinner:#,header:#DF7F78"
