# Scheme name: penumbra balanced eight dark
# Scheme system: 
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

set -l FZF_NON_COLOR_OPTS

for arg in (echo $FZF_DEFAULT_OPTS | tr " " "\n")
    if not string match -q -- "--color*" $arg
        set -a FZF_NON_COLOR_OPTS $arg
    end
end

set -Ux FZF_DEFAULT_OPTS "$FZF_NON_COLOR_OPTS"\
" --color=bg:#303338,fg:#F2E6D4,hl:#8D9741"\
" --color=bg+:#636363,fg+:#,hl+:#"\
" --color=info:#9481CC,border:#9481CC,prompt:#47A477"\
" --color=pointer:#5794D0,marker:#,spinner:#,header:#CA736C"
