# Scheme name: penumbra contrast+ eight dark
# Scheme system: 
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

set -l FZF_NON_COLOR_OPTS

for arg in (echo $FZF_DEFAULT_OPTS | tr " " "\n")
    if not string match -q -- "--color*" $arg
        set -a FZF_NON_COLOR_OPTS $arg
    end
end

set -Ux FZF_DEFAULT_OPTS "$FZF_NON_COLOR_OPTS"\
" --color=bg:#24272B,fg:#F2E6D4,hl:#9CA748"\
" --color=bg+:#636363,fg+:#,hl+:#"\
" --color=info:#A48FE1,border:#A48FE1,prompt:#50B584"\
" --color=pointer:#61A3E6,marker:#,spinner:#,header:#DF7F78"
