# -penumbra contrast++ eight light
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

export FZF_DEFAULT_OPTS=" \
 --color=bg:#FFF7ED,fg:#3E4044,hl:#A9B852\
 --color=bg+:#DEDEDE,fg+:#3E4044,hl+:#\
 --color=info:#,border:#6EB2FD,prompt:#54C794\
 --color=pointer:#FFF7ED,marker:#,spinner:#,header:#F58C81"
