# -penumbra balanced eight dark
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

export FZF_DEFAULT_OPTS=" \
 --color=bg:#303338,fg:#F2E6D4,hl:#8D9741\
 --color=bg+:#636363,fg+:#F2E6D4,hl+:#\
 --color=info:#,border:#5794D0,prompt:#47A477\
 --color=pointer:#303338,marker:#,spinner:#,header:#CA736C"
