# Scheme name: penumbra contrast++ eight light
# Scheme system: 
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

$ENV:FZF_DEFAULT_OPTS=@"
--color=bg:#FFF7ED,fg:#3E4044,hl:#A9B852
--color=bg+:#DEDEDE,fg+:#,hl+:#
--color=info:#B69CF6,border:#B69CF6,prompt:#54C794
--color=pointer:#6EB2FD,marker:#,spinner:#,header:#F58C81
"@
