# -penumbra balanced eight light
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

export FZF_DEFAULT_OPTS=" \
 --color=bg:#FFF7ED,fg:#3E4044,hl:#8D9741\
 --color=bg+:#BEBEBE,fg+:#3E4044,hl+:#\
 --color=info:#,border:#5794D0,prompt:#47A477\
 --color=pointer:#FFF7ED,marker:#,spinner:#,header:#CA736C"
