# Scheme name: penumbra contrast+ eight dark
# Scheme system: 
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

$ENV:FZF_DEFAULT_OPTS=@"
--color=bg:#24272B,fg:#F2E6D4,hl:#9CA748
--color=bg+:#636363,fg+:#,hl+:#
--color=info:#A48FE1,border:#A48FE1,prompt:#50B584
--color=pointer:#61A3E6,marker:#,spinner:#,header:#DF7F78
"@
