# -penumbra contrast++ eight dark
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

export FZF_DEFAULT_OPTS=" \
 --color=bg:#181B1F,fg:#F2E6D4,hl:#A9B852\
 --color=bg+:#636363,fg+:#F2E6D4,hl+:#\
 --color=info:#,border:#6EB2FD,prompt:#54C794\
 --color=pointer:#181B1F,marker:#,spinner:#,header:#F58C81"
