# Scheme name: penumbra contrast+ eight light
# Scheme system: 
# Scheme author: yushyin (generated by base16-penumbra-scheme-gen.pl)
# Template author: Tinted Theming (https://github.com/tinted-theming)

$ENV:FZF_DEFAULT_OPTS=@"
--color=bg:#FFF7ED,fg:#3E4044,hl:#9CA748
--color=bg+:#CECECE,fg+:#,hl+:#
--color=info:#A48FE1,border:#A48FE1,prompt:#50B584
--color=pointer:#61A3E6,marker:#,spinner:#,header:#DF7F78
"@
